spring.application.name=proyecto

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio_db
spring.datasource.username=gimnasio_db
spring.datasource.password=gimnasio_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# Limites para subida de ficheros (evitar HTTP 413 Payload Too Large)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Configuration
jwt.secret=tu_clave_secreta_muy_segura_cambiar_en_produccion
jwt.expiration=86400000
